## Numpy array and basics
learn about numpy

In [3]:
import numpy as np

### creating array from list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array", arr_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [18]:
py_list = [1,2,3]
print("Python list multiplication ", py_list*2)


np_array = np.array([1,2,3]) #element wise multiplication
print("Python array multiplication ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.1364607810974121

 Numpy operation time:  0.011982917785644531


### creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("zeros array:  \n", zeros)

ones = np.ones((2, 3))
print("ones array:  \n", ones)

full = np.full((2, 2), 7)
print("full array:  \n", full)

random = np.random.random((2,3))
print("random array:  \n", random)

sequence = np.arange(0, 10, 2) # 0 to 10 ke bich 2-2 ke gap pe jayega
print("sequence array:  \n", sequence)

zeros array:  
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:  
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:  
 [[7 7]
 [7 7]]
random array:  
 [[0.53395219 0.36209255 0.28117321]
 [0.18439951 0.88748479 0.82292753]]
sequence array:  
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [35]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3, 4]],
                   [[5, 6], [7, 8]]]) # tensor m dimension jyada hota h
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [37]:
arr = np.array([[1, 2 , 3],
                [4, 5, 6]])
print("Shape ", arr.shape) # shape find
print("Dimension ", arr.ndim) #dimension find
print("Size ", arr.size) # size means how much elements are there
print("DType ", arr.dtype) # to find data type

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshape array ", reshaped)

flattened = reshaped.flatten()
print("\n Flatten array ", flattened)

# ravel( returns view, instead of copy )
raveled = reshaped.ravel()
print("\n Raveled array ", raveled)

# Transpose

transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshape array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
