## Numpy Array operations


In [7]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing ", arr[2:7])
print("With step ", arr[1:8:2]) # 1 to 8 with every 2 steps
print("Negative indexing ", arr[-3])

Basic slicing  [3 4 5 6 7]
With step  [2 4 6 8]
Negative indexing  8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2]) # 1st row ka 2nd array jo ki 6 hai
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1]) # : isse coloumn target krte h like 1st array ka coloum jo ki 2, 5, 8 hai.


Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1],
                            [1, 2],
                            [2, 3]])
print("Sorted 2D array by coloumn: ", np.sort(arr_2d_unsorted, axis=0)) # axis = 0 means top to bottom sorting & axis = 1 means bottom to top sorting

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by coloumn:  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [23]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


## Filter with mask

In [24]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [27]:
indices = [0, 2, 4]
print(numbers[indices]) # indices se direct array[ value ] bhi print ho jaata h

where_result = np.where(numbers > 5)
print("NP Where ", numbers[where_result])

[1 3 5]
NP Where  [ 6  7  8  9 10]


In [31]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibqility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes ", a.shape == b.shape) # mxn = mxn

Compatibility shapes  True


In [42]:
original = np.array([[1, 2],
                     [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(original)
print("New row: ",with_new_row) # vstack hamesa row ( left to right ) add krta h.

new_col = np.array([[7],
                    [8]])
with_new_col = np.hstack((original, new_col))
print("New coloum: ", with_new_col) # hstack se new coloumn ( top to bottom ) add hota h


[[1 2]
 [3 4]]
New row:  [[1 2]
 [3 4]
 [5 6]]
New coloum:  [[1 2 7]
 [3 4 8]]


### Delete indexing

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])
deleted = np.delete(arr, 2) 
print("Array after deletion", deleted) 

Array after deletion [1 2 4 5 6]
